version: '2'

services:
  app_server:
    build: dev-ops/docker/containers/php7
    extra_hosts:
      - "rest-exitb-erp.blissdev.de:172.22.0.1"
    volumes:
      - ~/.composer/cache:/var/www/composer-cache-dir:Z
      - .:/project:Z
      - .:/var/www/shopware:Z
      - '/home/roman/workspace:/home/roman/workspace'
      - '/tmp:/tmp'
    links:
      - app_mysql:mysql
    environment:
      TERM: xterm
      COMPOSER_CACHE_DIR: /var/www/composer-cache-dir
    ports:
      - "8083:80"
    networks:
      - dev_net

  app_mysql:
    build: dev-ops/docker/containers/mysql
    volumes:
      - ./dev-ops/docker/_volumes/app-mysql-data:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      - dev_net

  app_es:
    build: dev-ops/docker/containers/elastic-search
    volumes:
      - ./dev-ops/docker/containers/elastic-search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
      - ./dev-ops/docker/_volumes/app-es-data:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TERM: xterm
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - dev_net

  app_redis:
    build: dev-ops/docker/containers/redis
    volumes:
      - ./dev-ops/docker/_volumes/app-redisdata:/data:Z
    networks:
      - dev_net

networks:
  dev_net:
    ipam:
      driver: default
      config:
          - subnet: 172.22.0.0/16
